version: '2'

services:
  mysql:
    image: mysql:5.7.22
    restart: always
    volumes:
      - ./blindsqli.sql:/docker-entrypoint-initdb.d/blindsqli.sql
      - ./db-volume:/var/lib/mysql
      - ./mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    environment:
      - MYSQL_DATABASE=blindsqli
      - MYSQL_ROOT_PASSWORD=gdxfsm,xyxx
  web:
    build: .
    depends_on:
      - mysql
    ports:
      - '10013:80'
    volumes:
      - ./source:/var/www/html
      - ./logs:/var/log/apache2
    stdin_open: true

